// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261008110556_InitialCreateDatabase")]
    partial class InitialCreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Gạo, Nếp & Cốc loại",
                            Description = "Gạo ST25 Hồng Phát, gạo nở, nếp nương, đậu xanh"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Gia vị & Dầu ăn kho",
                            Description = "Nước mắm, nước tương, hạt nêm, đường, dầu ăn"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Mì, Phở & Thực phẩm ăn liền",
                            Description = "Mì gói, phở khô, bún tươi, hủ tiếu ăn liền"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Bánh kẹo & Đồ ăn vặt",
                            Description = "Bánh quy, kẹo dẻo, snack, hạt điều, mứt"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Nước giải khát & Trà",
                            Description = "Nước ngọt, nước khoáng, trà túi lọc, cà phê hòa tan"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Sữa & Sản phẩm từ sữa",
                            Description = "Sữa tươi, sữa đặc, sữa chua, phô mai"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Thực phẩm đóng hộp",
                            Description = "Cá hộp, thịt hộp, pate, ngô ngọt đóng hộp"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Hóa mỹ phẩm & Tắm giặt",
                            Description = "Xà bông, dầu gội, nước rửa chén, nước lau nhà"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Vệ sinh cá nhân",
                            Description = "Kem đánh răng, bàn chải, khăn giấy, khẩu trang"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Đồ dùng gia đình & Kho vận",
                            Description = "Băng dính đóng gói, túi rác, màng bọc thực phẩm"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Thực phẩm khô & Nông sản",
                            Description = "Nấm hương, mộc nhĩ, tôm khô, măng khô"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Gia vị tươi & Đồ sơ chế",
                            Description = "Hành, tỏi, ớt, sả, gừng đóng gói"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Đồ uống có cồn & Bia",
                            Description = "Bia lon, rượu nếp, rượu vang Hồng Phát"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Đồ mẹ và bé",
                            Description = "Tã bỉm, tăm bông em bé, khăn giấy ướt"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Nến, Hương & Đồ thờ cúng",
                            Description = "Hương thắp, nến cốc, giấy cúng gia đình"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "123 Lê Lợi, Quận 1, TP.HCM",
                            CustomerName = "Nguyễn Văn An",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0912345678",
                            RewardPoints = 350
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "456 Nguyễn Trãi, Quận 5, TP.HCM",
                            CustomerName = "Trần Thị Bình",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0987654321",
                            RewardPoints = 1200
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "789 Võ Văn Tần, Quận 3, TP.HCM",
                            CustomerName = "Lê Hoàng Cường",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0903112233",
                            RewardPoints = 50
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "12 Điện Biên Phủ, Bình Thạnh, TP.HCM",
                            CustomerName = "Phạm Minh Dung",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0938889900",
                            RewardPoints = 750
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "88 Lý Thường Kiệt, Tân Bình, TP.HCM",
                            CustomerName = "Hoàng Quốc Dung",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0977123456",
                            RewardPoints = 0
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "54 CMT8, Quận 10, TP.HCM",
                            CustomerName = "Đỗ Thị Giang",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0966554433",
                            RewardPoints = 150
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "301 Hải Phòng, Thanh Khê, Đà Nẵng",
                            CustomerName = "Vũ Hải Đăng",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0944118899",
                            RewardPoints = 520
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "15 Trần Hưng Đạo, Hoàn Kiếm, Hà Nội",
                            CustomerName = "Ngô Bích Hằng",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0918273645",
                            RewardPoints = 2100
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "67 Nguyễn Văn Cừ, Long Biên, Hà Nội",
                            CustomerName = "Bùi Anh Tuấn",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0922334455",
                            RewardPoints = 890
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "234 Ba Tháng Hai, Quận 10, TP.HCM",
                            CustomerName = "Đặng Thu Thảo",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0955667788",
                            RewardPoints = 410
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "11 Phạm Văn Đồng, Thủ Đức, TP.HCM",
                            CustomerName = "Trịnh Quốc Bảo",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0909090909",
                            RewardPoints = 30
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "89 Nguyễn Thị Minh Khai, Quận 3, TP.HCM",
                            CustomerName = "Lý Mỹ Nhân",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0933221100",
                            RewardPoints = 1050
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "43 Quang Trung, Gò Vấp, TP.HCM",
                            CustomerName = "Dương Văn Khoa",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0978990011",
                            RewardPoints = 620
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "500 Nam Kỳ Khởi Nghĩa, Quận 3, TP.HCM",
                            CustomerName = "Mai Phương Thúy",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0911223344",
                            RewardPoints = 1850
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "76 Nguyễn Văn Linh, Quận 7, TP.HCM",
                            CustomerName = "Cao Thái Sơn",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0945678901",
                            RewardPoints = 95
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "HP8935001001",
                            CategoryId = 1,
                            Price = 185000m,
                            ProductName = "Gạo ST25 Hồng Phát Đặc Sản 5kg",
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "HP8935001002",
                            CategoryId = 2,
                            Price = 32000m,
                            ProductName = "Nước mắm Nam Ngư Đột Phá 500ml",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "HP8935001003",
                            CategoryId = 3,
                            Price = 118000m,
                            ProductName = "Mì Hảo Hảo Tôm Chua Cay (Thùng 30 gói)",
                            StockQuantity = 85
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "HP8935001004",
                            CategoryId = 4,
                            Price = 18000m,
                            ProductName = "Bánh quy OREO vị Vani 133g",
                            StockQuantity = 150
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "HP8935001005",
                            CategoryId = 5,
                            Price = 10000m,
                            ProductName = "Nước khoáng Lavie 1.5L",
                            StockQuantity = 300
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "HP8935001006",
                            CategoryId = 6,
                            Price = 38000m,
                            ProductName = "Sữa tươi Vinamilk Có Đường 1L",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "HP8935001007",
                            CategoryId = 7,
                            Price = 28000m,
                            ProductName = "Cá ngừ ngâm dầu Hạ Long 175g",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "HP8935001008",
                            CategoryId = 8,
                            Price = 30000m,
                            ProductName = "Nước rửa chén Sunlight Chanh 750ml",
                            StockQuantity = 110
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "HP8935001009",
                            CategoryId = 9,
                            Price = 25000m,
                            ProductName = "Kem đánh răng PS Bảo Vệ 123 180g",
                            StockQuantity = 140
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "HP8935001010",
                            CategoryId = 10,
                            Price = 35000m,
                            ProductName = "Túi rác sinh học Hồng Phát 1kg",
                            StockQuantity = 95
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "HP8935001011",
                            CategoryId = 11,
                            Price = 45000m,
                            ProductName = "Nấm hương khô Cao Bằng 100g",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "HP8935001012",
                            CategoryId = 12,
                            Price = 22000m,
                            ProductName = "Tỏi Lý Sơn đóng gói 200g",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "HP8935001013",
                            CategoryId = 13,
                            Price = 105000m,
                            ProductName = "Bia Tiger Lon 330ml (Lốc 6 lon)",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "HP8935001014",
                            CategoryId = 14,
                            Price = 42000m,
                            ProductName = "Khăn giấy ướt Bobby 100 tờ",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "HP8935001015",
                            CategoryId = 15,
                            Price = 25000m,
                            ProductName = "Hương trầm thảo mộc Hồng Phát 100 nén",
                            StockQuantity = 100
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
